Zap unreferenced 'import test' in setup.py: breaks 'pip install'. The 'import test' in setup.py prevents us from using 'pip install' to install this package, at least on Windows with python.org Python 2.6:
C:\linden>pip install llbase
Downloading/unpacking llbase
  Downloading llbase-0.2.0.tar.gz (53Kb): 53Kb downloaded
  Running setup.py egg_info for package llbase
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "C:\home\virtualenvs\vita\build\llbase\setup.py", line 8, in <module>
        import test
    ImportError: No module named test

But as the unqualified name 'test' is never mentioned again, seems like we can
safely delete its import attempt without adverse effects.